name: Terraform Destroy EC2 Instance

on:
  workflow_dispatch: 
permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  
      - name: Set up AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }} 

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Plan 
      - name: Terraform Plan
        run: terraform plan

      # Destroy specific resource or all resources
      - name: Terraform Destroy
        run: |
         terraform destroy -auto-approve
        
