name: Terraform Destroy EC2 Instance

on:
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      destroy_all:
        description: 'Should we destroy all resources?'
        required: false
        default: 'false'
      resource:
        description: 'Specific resource to destroy (e.g., aws_instance.my_instance)'
        required: false
        default: 'aws_instance.my_instance'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Adjust based on your required version
      - name: Set up AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }} 

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Plan (optional)
      - name: Terraform Plan
        run: terraform plan

      # Destroy specific resource or all resources
      - name: Terraform Destroy
        run: |
          if [ "${{ github.event.inputs.destroy_all }}" == "true" ]; then
            echo "Destroying all resources..."
            terraform destroy -auto-approve
          else
            echo "Destroying specific resource: ${{ github.event.inputs.resource }}"
            terraform destroy -target=${{ github.event.inputs.resource }} -auto-approve
          fi
