name: Terraform Create EC2 Instance

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Adjust the version based on your needs
      - name: Set up AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }} 

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Plan (optional, but a good practice)
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply to create EC2 instance
      - name: Terraform Apply
        run: terraform apply -auto-approve
